--
-- PostgreSQL database dump
--

-- Dumped from database version 17.1
-- Dumped by pg_dump version 17.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Bookings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Bookings" (
    id integer NOT NULL,
    userid integer NOT NULL,
    username character varying(100) NOT NULL,
    useremail character varying(100) NOT NULL,
    tableid integer NOT NULL,
    capacity integer NOT NULL,
    bookingdatetime timestamp without time zone NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public."Bookings" OWNER TO postgres;

--
-- Name: Bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Bookings_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Bookings_id_seq" OWNER TO postgres;

--
-- Name: Bookings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Bookings_id_seq" OWNED BY public."Bookings".id;


--
-- Name: CartItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CartItems" (
    id integer NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT cart_items_quantity_check CHECK ((quantity > 0))
);


ALTER TABLE public."CartItems" OWNER TO postgres;

--
-- Name: Orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orders" (
    id integer NOT NULL,
    userid integer,
    orderdate timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    totalprice numeric(10,2),
    pickupaddress character varying(255),
    paymentmethod character varying(20),
    status character varying(50) DEFAULT 'В обработке'::character varying,
    orderdescription text
);


ALTER TABLE public."Orders" OWNER TO postgres;

--
-- Name: Orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Orders_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Orders_id_seq" OWNER TO postgres;

--
-- Name: Orders_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Orders_id_seq" OWNED BY public."Orders".id;


--
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cart_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cart_items_id_seq OWNER TO postgres;

--
-- Name: cart_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cart_items_id_seq OWNED BY public."CartItems".id;


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name text NOT NULL,
    category text NOT NULL,
    price numeric(10,2) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    description text,
    imageurl character varying(255),
    weight integer DEFAULT 0 NOT NULL,
    ishidden boolean DEFAULT false NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public."Users"."Id";


--
-- Name: Bookings id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Bookings" ALTER COLUMN id SET DEFAULT nextval('public."Bookings_id_seq"'::regclass);


--
-- Name: CartItems id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems" ALTER COLUMN id SET DEFAULT nextval('public.cart_items_id_seq'::regclass);


--
-- Name: Orders id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders" ALTER COLUMN id SET DEFAULT nextval('public."Orders_id_seq"'::regclass);


--
-- Name: Users Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users" ALTER COLUMN "Id" SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: products id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- Data for Name: Bookings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Bookings" (id, userid, username, useremail, tableid, capacity, bookingdatetime, createdat) FROM stdin;
\.


--
-- Data for Name: CartItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CartItems" (id, user_id, product_id, quantity) FROM stdin;
\.


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Orders" (id, userid, orderdate, totalprice, pickupaddress, paymentmethod, status, orderdescription) FROM stdin;
14	11	2025-06-12 11:04:23.857193	9.50	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Готово	Раф 320мл - 1 шт
13	11	2025-06-12 11:04:19.191694	13.80	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Готово	Двойной эспрессо 50мл - 1 шт, Фильтр-кофе 300 300мл - 1 шт
11	11	2025-06-12 11:03:58.124155	8.50	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Готово	Пряный кофе 180мл - 1 шт
12	11	2025-06-12 11:04:12.88505	49.50	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Отменён	Пряный кофе 180мл - 1 шт, Латте нутелла 320мл - 1 шт, Пирожное "Павлова" 80гр - 2 шт, Киш с курицей и французской горчицей 140гр - 1 шт
15	12	2025-06-12 11:58:57.029641	7.50	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Готово	Фильтр-кофе 300 300мл - 1 шт
16	12	2025-06-12 12:10:48.750626	8.50	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	В обработке	Двойной капучино 320мл - 1 шт
17	11	2025-06-20 10:36:51.649571	14.20	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	В обработке	Фильтр-кофе 300 300мл - 1 шт, Австралийский лунго 150мл - 1 шт
10	11	2025-06-12 10:50:30.953828	6.30	ул. Карла Маркса 9, Минск, Минская область 220036, Беларусь	pickup	Готово	Американо 180мл - 1 шт
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Products" ("Id", "Name", "Price") FROM stdin;
1	Лате	1
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "PasswordHash") FROM stdin;
11	Алексей	alexalexey914@gmail.com	AQAAAAIAAYagAAAAENx/hXIIIWxtVJns/rC7nhI9ysVlRVl8uYEzfoty+U2CR3aagr7CWIxSI3eZzgHJqw==
12	Николай Радзивилл Черный	abdur0ss1k@gmail.com	AQAAAAIAAYagAAAAEA2bYhqXf7VGFA87L0maL/BgU1/URi7wmP+hBhzAFp5GaK6FP0+Jp0eV4mfrUPtEAQ==
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250226053208_InitialCreate	9.0.2
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, category, price, createdat, description, imageurl, weight, ishidden) FROM stdin;
2	Двойной эспрессо	Coffee	6.30	2025-03-06 10:54:29.994277	Яркий и насыщенный концентрированный напиток, приготовленный в эспрессо-машине, кофе натуральной обработки. Обладает низкой кислотностью и плотным округлым телом.\r\nЗерно: Арабика, Пер	/images/DuEsp.jpg	50	f
6	Фильтр-кофе 300	Coffee	7.50	2025-03-06 10:56:27.654495	Крепкий черный кофе сваренный капельным путем.	/images/Flet.jpg	300	f
20	Пирожное «Картошка c арахисом»	Dessert	7.00	2025-03-06 12:41:39.493092	Сахар, мука, яйцо, какао, масло сливочное, масло растительное, молоко, сода, соль, уксус, молоко сгущённое, тёмный шоколад, соленый арахис, коньяк, ром.	/images/Kartoh.jpg	65	f
7	Фильтр-кофе 400	Coffee	8.50	2025-03-06 10:58:00.045767	Крепкий черный кофе сваренный капельным путем.	/images/Flet.jpg	400	f
8	Капучино	Coffee	7.50	2025-03-06 11:09:39.712699	Классический кофейно-молочный напиток на основе эспрессо с добавлением вспененного молока.	/images/Kap.jpg	250	f
9	Двойной капучино	Coffee	8.50	2025-03-06 11:10:18.884551	Классический кофейно-молочный напиток на основе двойного эспрессо с добавлением вспененного молока.	/images/DuKap.jpg	320	f
10	Какао	Coffee	6.50	2025-03-06 11:17:05.764072	Насыщенный вкус натурального какао.	/images/Cacao.jpg	250	f
11	Раф	Coffee	9.50	2025-03-06 11:17:31.203341	Сливочный кофейный напиток со сладким ванильным ароматом и воздушной текстурой.	/images/Raf.jpg	320	f
12	Флэт Уайт	Coffee	6.00	2025-03-06 11:17:58.55573	Напиток с выраженным ярким и насыщенным вкусом двойного эспрессо в сочетании со сладким, слегка взбитым, молоком.	/images/Wayt.jpg	200	f
13	Латте	Coffee	8.50	2025-03-06 11:18:55.547017	Напиток с выраженным вкусом сладкого взбитого молока, нежной молочной пеной и порцией эспрессо.	/images/Latte.jpg	320	f
14	Двойной латте	Coffee	10.00	2025-03-06 11:19:19.828298	Напиток с выраженным вкусом сладкого взбитого молока, нежной молочной пеной и двойной порцией эспрессо.	/images/DuLatte.jpg	450	f
15	Пряный кофе	Coffee	8.50	2025-03-06 11:25:11.276857	Ароматный пряный чёрный кофе с яркой фруктовой кислотностью и коньячными нотами.	/images/Prian.jpg	180	f
16	Латте нутелла	Coffee	10.00	2025-03-06 11:25:36.893868	Легкий кофейно-молочный напиток с шоколадно-ореховым вкусом.	/images/Nutel.jpg	320	f
17	Виноградный кофейный пунш	Coffee	9.00	2025-03-06 11:26:10.387529	Горячий кофейный напиток на основе фильтр-кофе с фруктовым вкусом.	/images/Punsh.jpg	250	f
18	 Глинтвейн	Coffee	12.00	2025-03-06 11:26:32.965638	Легкоалкогольный напиток на основе красного вина и пряностей.	/images/Glint.jpg	300	f
21	Печенье с фундуком и молочным шоколадом	Dessert	4.00	2025-03-06 12:42:02.911897	Мука, масло сливочное, сахар, яйца, фундук, вишня сушеная, соль, молочный шоколад.\r\nКБЖУ ( в 100 гр.): 437,54/	/images/funduk.jpg	35	f
22	Пирожное "Павлова"	Dessert	9.00	2025-03-06 12:42:32.198786	Белки яичные, сахар, сахарная пудра, крахмал кукурузный, лимонный концентрат, малина, замороженная, пектин, маскарпоне, сливки натуральные, фисташки молотые, свежая голубика, кумкват.	/images/Pavlova.jpg	80	f
1	Эспрессо	Coffee	6.00	2025-03-06 11:07:19.957318	Наш эспрессо — это концентрированный напиток небольшого объёма, кофе натуральной обработки. Обладает низкой кислотностью и плотным округлым телом.	/images/Esp.jpg	30	f
25	Чизкейк «Классический»	Dessert	10.00	2025-03-06 12:43:50.037526	Крем-чиз, сахар, яйцо, сметана, печенье, масло сливочное.	/images/Klass.jpg	100	f
23	Торт «Медовик»	Dessert	10.00	2025-03-06 12:42:55.634951	Сахар, сливочное масло, мука, яйцо, мёд натуральный, сливки натуральные, сметана.	/images/Medovik.jpg	100	f
24	Торт «Наполеон»	Dessert	10.00	2025-03-06 12:43:18.351273	сахар, мука, соль, масло сливочное, яйцо, молоко, крахмал кукурузный, ванилин, желатиновая масса.	/images/Napalion.jpg	100	f
26	Макарон «Ванильный с малиной»	Dessert	7.00	2025-03-06 12:55:54.957937	Миндальная мука, сахарная пудра, яичный белок, сахар, масло сливочное, ваниль, краситель (по желанию), начинка (крем на основе сливочного сыра или ганаша).	/images/Vanil.jpg	30	f
5	Фильтр-кофе 200	Coffee	6.50	2025-03-06 11:09:08.551294	 Крепкий черный кофе сваренный капельным путем.	/images/Flet.jpg	200	f
27	Макарон «Манго-маракуйя»	Dessert	7.00	2025-03-06 12:56:16.456103	Миндальная мука, сахарная пудра, яичный белок, сахар, масло сливочное, ваниль, краситель (по желанию), начинка (крем на основе сливочного сыра или ганаша).	/images/Mang.jpg	30	f
4	Австралийский лунго	Coffee	6.70	2025-03-06 11:08:49.585507	Крепкий чёрный кофе с яркой ягодной кислотностью.	/images/Avst.jpg	150	f
3	Американо	Coffee	6.30	2025-03-06 10:55:01.369923	Классический черный кофе на основе двойного эспрессо с добавлением воды.	/images/Amer.jpg	180	f
28	Макарон "Дубайский"	Dessert	7.50	2025-03-06 12:56:47.679342	Миндальная мука, какао, сахарная пудра, яичный белок, сахар, альбумин, молочный шоколад, темный шоколад, сливки, желатин, фисташка, растительное масло, сироп фисташковый, тесто катаифи, сливочное масло	/images/Dub.jpg	55	f
29	Кекс «Лимонный»	Dessert	9.50	2025-03-06 12:57:16.982158	мука, яйцо, сахар, масло сливочное, цедра лимона, лимонный сок, сливки, белый шоколад, желатин, растительное масло.	/images/Limo.jpg	80	f
30	Тарталетка «Тирамису»	Dessert	12.00	2025-03-06 12:58:22.961374	Сливки, кофе, молочный шоколад, желатин, маскарпоне, глюкозный сироп, белый шоколад, белок яичный, сахар, мука, крахмал, желток, сахарная пудра.	/images/Tirami.jpg	120	f
19	Печенье «Овсяное»	Dessert	4.00	2025-03-06 12:41:05.555225	Мука, сахар, масло сливочное, яйца, хлопья овсяные, шоколад белый, клюква сушеная, пекарский порошок, ванилин.	/images/Ofsia.jpg	35	f
31	Киш с моцареллой и черри	Dish	13.00	2025-03-11 10:02:11.001862	Открытый французский пирог на рассыпчатой песочной основе с начинкой из грудинки, свежих овощей, сыра моцарелла под сливочно-яичной заливкой.	/images/Mosa.jpg	150	f
32	Киш с красной рыбой и брокколи	Dish	14.00	2025-03-11 10:02:49.42936	Открытый французский пирог с лососем и брокколи в сливочно-яичной заливке на основе из рубленого теста.	/images/Rib.jpg	140	f
33	Киш с курицей и французской горчицей	Dish	13.00	2025-03-11 10:03:57.420153	Открытый французский пирог на рассыпчатой песочной основе с сочной начинкой из куриного фарша с шампиньонами и французской горчицей под сливочно-яичной заливкой.	/images/Kuris.jpg	140	f
34	Круассан классический	Dish	3.80	2025-03-11 10:04:26.041088	Французская выпечка с хрустящей корочкой, рассыпающейся на множество лепестков, и нежным воздушным мякишем.	/images/Kuris.jpg	60	f
40	Сэндвич с беконом и сыром	Dish	17.00	2025-03-11 10:16:58.122857	Классическое сочетание хрустящего поджаренного хлеба, ароматного жареного бекона и расплавленного сыра. 	/images/Bekon.jpg	265	f
35	 Круассан «нутелла» и банан	Dish	8.00	2025-03-11 10:08:34.856503	Воздушная и хрустящая выпечка, наполненная нежным шоколадно-ореховым кремом «Нутелла» и кусочками свежего банана.	/images/Nutela.jpg	100	f
36	Круассан арахисовая паста и банан	Dish	8.00	2025-03-11 10:08:50.648584	Аппетитное сочетание хрустящей слоёной выпечки, насыщенного орехового вкуса и сладости спелого банана. 	/images/Banana.jpg	100	f
37	 Круассан малиновый соус и творожный сыр	Dish	8.00	2025-03-11 10:09:32.208574	Изысканное сочетание хрустящей слоёной выпечки, нежного сливочного сыра и яркого ягодного вкуса. 	/images/Malina.jpg	90	f
38	Сырники сладкие с греческим йогуртом	Dish	13.00	2025-03-11 10:09:55.838435	 Нежные творожные сырники с румяной корочкой на рисовой муке. Посыпаются сахарной пудрой и подается с греческим йогуртом	/images/Sirnik.jpg	230	f
39	Круассан "Капрезе"	Dish	13.00	2025-03-11 12:01:51.652013	Оригинальная интерпретация классического итальянского салата в сочетании с воздушной слоёной выпечкой. Внутри хрустящего круассана скрываются сочные ломтики свежих томатов, нежная моцарелла и ароматный соус песто. 	/images/Kapresa.jpg	145	f
41	Блины со сливочной индейкой и шампиньонами	Dish	17.00	2025-03-11 12:05:06.122625	Нежные тонкие блинчики, начинённые сочным филе индейки и ароматными шампиньонами в кремовом соусе. 	/images/Inde.jpg	275	f
42	Творожные блины с шариком ванильного мороженого и сладким вишневым соусом	Dish	15.00	2025-03-11 12:14:57.643525	Нежные, слегка воздушные блинчики с творожной начинкой, которые идеально сочетаются с прохладным сливочным мороженым и густым ароматным вишнёвым соусом.	/images/Blin.jpg	290	f
\.


--
-- Name: Bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Bookings_id_seq"', 41, true);


--
-- Name: Orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Orders_id_seq"', 17, true);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 1, true);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 56, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 43, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 12, true);


--
-- Name: Bookings Bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT "Bookings_pkey" PRIMARY KEY (id);


--
-- Name: Orders Orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_pkey" PRIMARY KEY (id);


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: CartItems cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: CartItems unique_user_product; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT unique_user_product UNIQUE (user_id, product_id);


--
-- Name: Users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_email_key UNIQUE ("Email");


--
-- Name: Users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_pkey PRIMARY KEY ("Id");


--
-- Name: Orders Orders_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_userid_fkey" FOREIGN KEY (userid) REFERENCES public."Users"("Id");


--
-- Name: CartItems fk_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: CartItems fk_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

